- name: Install required packages
  apt:
    name: ['docker.io', 'python3-pip', 'ufw']
    state: present
    update_cache: yes

- name: Install Docker Compose v2
  ansible.builtin.command:
    cmd: curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

- name: Set executable permissions for Docker Compose
  file:
    path: /usr/local/bin/docker-compose
    mode: '0755'
    state: file

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add current user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reset ssh connection
  meta: reset_connection
