- name: Enable UFW firewall and allow OpenSSH
  ufw:
    state: enabled
    rule: allow
    name: 'OpenSSH'

- name: Allow HTTP (80) port in UFW
  ufw:
    state: enabled
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS (443) port in UFW
  ufw:
    state: enabled
    rule: allow
    port: 443
    proto: tcp

- name: Allow port 3306 (MySQL) only on localhost (security)
  ufw:
    rule: allow
    from_ip: 127.0.0.1
    to_port: 3306
    proto: tcp