version: "3.5"

services:

    mariadb:
      build: ./requirements/MariaDB
      container_name: mariadb
      # ports: [3306:3306]
      # image: mariadb
      env_file: .env
      restart: unless-stopped
      volumes:
        - mariadb:/var/lib/mysql
      networks:
        - app-network

    wordpress:
      build: ./requirements/wordpress
      container_name: wordpress
      # ports: [9000:9000]
      # image: wordpress
      depends_on:
        - mariadb
      restart: unless-stopped
      env_file: .env

      networks:
        - app-network
      volumes:
        - wordpress:/var/www/html/wordpress

    nginx:
      build: ./requirements/nginx
      container_name: nginx
      ports: [443:443]
      # image: nginx
      restart: unless-stopped
      depends_on:
        - wordpress
      networks:
        - app-network
      volumes:
        - wordpress:/var/www/html/wordpress

volumes:
        wordpress:
            name: wordpress
            driver: local
            driver_opts:
              type: none
              o: bind
              device: /home/ubuntu/data/wordpress
        mariadb:
            name: mariadb
            driver: local
            driver_opts:
              type: none
              o: bind
              device: /home/ubuntu/data/mariadb


networks:
  app-network:
    driver: bridge
