---
- name: Ensure /home/ubuntu/data/wordpress directory exists
  file:
    path: /home/ubuntu/data/wordpress
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Ensure /home/ubuntu/data/mariadb directory exists
  file:
    path: /home/ubuntu/data/mariadb
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy Dockerized WordPress project to remote server
  copy:
    src: "{{ playbook_dir }}/../inception/src/"
    dest: /home/ubuntu/src/
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Ensure docker is installed on the remote server
  package:
    name: docker.io
    state: present

- name: Create directory for Docker CLI plugins
  file:
    path: /usr/libexec/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Install Docker Compose plugin
  ansible.builtin.command:
    cmd: curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o /usr/libexec/docker/cli-plugins/docker-compose
  args:
    creates: /usr/libexec/docker/cli-plugins/docker-compose

- name: Set executable permissions for Docker Compose plugin
  file:
    path: /usr/libexec/docker/cli-plugins/docker-compose
    mode: '0755'
    state: file

- name: Run Docker Compose to start the WordPress site
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/src/
    state: present
    recreate: auto
    remove_orphans: true

# - name: Enable UFW firewall and allow OpenSSH
#   ufw:
#     state: enabled
#     rule: allow
#     name: 'OpenSSH'

# - name: Allow HTTP (80) port in UFW
#   ufw:
#     state: enabled
#     rule: allow
#     port: 80
#     proto: tcp

# - name: Allow HTTPS (443) port in UFW
#   ufw:
#     state: enabled
#     rule: allow
#     port: 443
#     proto: tcp

# - name: Allow port 3306 (MySQL) only on localhost (security)
#   ufw:
#     rule: allow
#     from_ip: 127.0.0.1
#     to_port: 3306
#     proto: tcp
# - name: Enable UFW
#   ufw:
#     state: enabled
#     policy: allow
# - name: Enable UFW firewall and allow OpenSSH
#   ufw:
#     state: enabled
#     rule: allow
#     name: 'OpenSSH'

# - name: Allow HTTP (80) port in UFW
#   ufw:
#     state: enabled
#     rule: allow
#     port: 80
#     proto: tcp

# - name: Allow HTTPS (443) port in UFW
#   ufw:
#     state: - name: Enable UFW
  # ufw:
  #   state: enabled
  #   policy: allowenabled
#     rule: allow
#     port: 443
#     proto: tcp

# - name: Allow port 3306 (MySQL) only on localhost (security)
#   ufw:
#     rule: allow
#     from_ip: 127.0.0.1
#     to_port: 3306
#     proto: tcp