---
- name: Copy Dockerized WordPress project to remote server
  copy:
    src: "{{ playbook_dir }}/../inception/src/"
    dest: /home/ubuntu/src/
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Ensure docker is installed on the remote server
  package:
    name: docker.io
    state: present

- name: Create directory for Docker CLI plugins
  file:
    path: /usr/libexec/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Install Docker Compose plugin
  ansible.builtin.command:
    cmd: curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o /usr/libexec/docker/cli-plugins/docker-compose
  args:
    creates: /usr/libexec/docker/cli-plugins/docker-compose

- name: Set executable permissions for Docker Compose plugin
  file:
    path: /usr/libexec/docker/cli-plugins/docker-compose
    mode: '0755'
    state: file

- name: Run Docker Compose to start the WordPress site
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/src/
    state: present
    recreate: auto
    remove_orphans: true
